#!/usr/bin/env python3
"""Emits the PRISMA 2020 flow from facts.json — the same numbers as the manuscript.

Not from `phd export prisma`: that command counts screening decisions rather than
screened records, and it has no notion of the sampling draws, the accessibility
gate or the integrity check, so it would hand a reviewer a supplementary file
that contradicts the paper.

Every number here comes from facts.json, which 101-verify.py recomputes
independently. The flow and the prose cannot disagree, because they read the
same file.

THE SAMPLING STAGES ARE IN THE FLOW, not in a footnote. Two seeded draws remove
more records than every exclusion criterion combined, and a flow diagram that
showed only the criteria would be arithmetically consistent and substantively
false about what happened.
"""
import json, pathlib

HERE = pathlib.Path(__file__).parent
# In the replication package the study data sits in ../data while the
# scripts stay in ../scripts. DATA is the only path that differs from
# the layout these scripts were executed in.
DATA = (HERE / ".." / "data").resolve()
F = json.loads((DATA / "facts.json").read_text())
OUT = (DATA / ".." / ".." / "docs" / "manuscript-agentmem").resolve()
OUT.mkdir(parents=True, exist_ok=True)

excl = {k[4:]: v for k, v in F.items()
        if k.startswith("Excl") and k[4:].startswith("E")}
order = sorted(excl.items(), key=lambda kv: -kv[1])
assessed = F["Drawn"] - F["IntegrityFlagged"]

md = f"""# PRISMA 2020 flow

Generated by `scripts/agentmem/102-prisma.py` from `facts.json`. Do not edit.
Every figure is recomputed independently by `scripts/agentmem/101-verify.py`.

## Identification

- Records returned by the databases: **{F['GrossHits']}**, across {F['Runs']}
  (query, provider) runs — {F['Queries']} queries against {F['Providers']} libraries.
- Runs that returned exactly their fetch cap: **{F['CapBound']} of {F['Runs']}**
  ({F['CapBoundPct']}%). Every strand is therefore a relevance-ranked slice of a
  larger match set.
- Distinct records after provider and title de-duplication: **{F['Identified']}**.

## Automated scope filter

One criterion applied to title and abstract: the record must carry a memory term
in the agent-state sense **and** name an LLM or agent system.

- Excluded: **{F['ScopeDropped']}**
- Title-identical duplicates collapsed: **{F['DuplicatesRemoved']}**
  (from **{F['TitleIdenticalGroups']}** colliding groups)
- Records in the screening pool: **{F['ScopeKept']}**, of which
  **{F['BranchGeneric']}** survived only on the loose branch, naming no memory
  construct from the term list — the evidence that the query set does not bound
  the corpus.

## Sampling into screening

- Seeded random draw, seed **{F['Seed']}**, committed before the draw.
- Drawn: **{F['Screened']}**. Not drawn: **{F['NotDrawnScreening']}**.

## Screening (title and abstract)

- Records screened: **{F['Screened']}**
- Excluded: **{F['Excluded']}**, with reasons:
"""
for c, n in order:
    md += f"  - **{c}**: {n}\n"
md += f"""  - A decision may cite more than one criterion, so these can sum above the total.
- Records included: **{F['Included']}** ({F['IncludeRate']}%)

### Screening reliability (test–retest)

The {F['PilotSize']}-record pilot was screened twice by independent coders, before
and after the pilot's feedback amended two decision rules. Raw agreement
**{F['RetestAgreement']}%**, Cohen's kappa **{F['RetestKappa']}**,
**{F['RetestDisagreements']}** disagreement.

## Accessibility gate

Full text fetched for every screening include; a record whose text could not be
retrieved is excluded here rather than carried forward unread.

- Text retrieved: **{F['GateIn']}**
- Excluded, no retrievable text: **{F['GateOut']}**

### Text-integrity check

- Records checked (title against extracted front matter): **{F['IntegrityChecked']}**
- Flagged as another paper's text and dropped: **{F['IntegrityFlagged']}**

## Sampling into classification

- Seeded random draw, seed **{F['Seed']}**, committed before the draw.
- Drawn: **{F['Drawn']}**. Not drawn: **{F['NotDrawnClassification']}**.
- Of the drawn, **{F['IntegrityFlagged']}** was dropped by the integrity check,
  leaving **{assessed}** to be read.

## Eligibility (full text)

- Reports assessed: **{assessed}**
- Excluded: **{F['Ineligible']}**
- Eligible: **{F['Corpus']}**

## Included in the map

- Papers in the map: **{F['Corpus']}**
- Facet assignments: **{F['Assignments']}**
- Second-coded for agreement: **{F['KappaN']}** ({F['KappaSharePct']}% of the corpus)
"""
(OUT / "prisma.md").write_text(md)

dot = f"""digraph prisma {{
  rankdir=TB; node [shape=box, fontname="Helvetica", fontsize=10, width=3];
  id   [label="Records returned by databases\\nn = {F['GrossHits']}\\n({F['Queries']} queries x {F['Providers']} libraries, {F['Runs']} runs)"];
  uniq [label="Distinct records\\nn = {F['Identified']}"];
  pool [label="Screening pool\\nn = {F['ScopeKept']}"];
  scr  [label="Screened\\nn = {F['Screened']}"];
  inc  [label="Included at screening\\nn = {F['Included']}"];
  gate [label="Full text retrieved\\nn = {F['GateIn']}"];
  drawn[label="Assessed for eligibility on full text\\nn = {assessed}\\n({F['Drawn']} drawn, {F['IntegrityFlagged']} dropped by the integrity check)"];
  fin  [label="Papers in the map\\nn = {F['Corpus']}", style=bold];
  xdup [label="Duplicate provider hits removed\\nn = {F['GrossHits'] - F['Identified']}"];
  xsco [label="Excluded by scope filter\\nn = {F['ScopeDropped']}\\nTitle-identical duplicates\\nn = {F['DuplicatesRemoved']}"];
  xsam [label="Not drawn (seeded sample)\\nn = {F['NotDrawnScreening']}", style=dashed];
  xscr [label="Excluded at screening\\nn = {F['Excluded']}"];
  xgat [label="No retrievable text\\nn = {F['GateOut']}"];
  xsa2 [label="Not drawn (seeded sample)\\nn = {F['NotDrawnClassification']}\\nText-integrity drop n = {F['IntegrityFlagged']}", style=dashed];
  xeli [label="Excluded at eligibility\\nn = {F['Ineligible']}"];
  id -> uniq -> pool -> scr -> inc -> gate -> drawn -> fin;
  {{rank=same; uniq; xdup}} {{rank=same; pool; xsco}} {{rank=same; scr; xsam}}
  {{rank=same; inc; xscr}} {{rank=same; gate; xgat}} {{rank=same; drawn; xsa2}}
  {{rank=same; fin; xeli}}
  uniq -> xdup; pool -> xsco; pool -> xsam; inc -> xscr; gate -> xgat;
  gate -> xsa2; drawn -> xeli;
}}
"""
(OUT / "prisma.dot").write_text(dot)
print(f"wrote {OUT/'prisma.md'} and prisma.dot")
print(f"  {F['GrossHits']} -> {F['Identified']} -> {F['ScopeKept']} -> {F['Screened']}"
      f" -> {F['Included']} -> {F['GateIn']} -> {assessed} -> {F['Corpus']}")
